CREATE TABLE USERS (

  ID INTEGER IDENTITY   ,
  USERNAME VARCHAR(32) NOT NULL UNIQUE ,
  PASSWORD VARCHAR(32) NOT NULL,
  ENABLED TINYINT NOT NULL,
  CREATE_DATE TIMESTAMP  not null
);


CREATE TABLE AUTHORITIES (
  id integer identity,
  USERNAME VARCHAR(32) not null ,
  AUTHORITY varchar(32) not null
);

CREATE TABLE DEPOT (

  ID INTEGER IDENTITY  ,
  USER_ID INTEGER NOT NULL ,
  DRAW_DATE DATE not null,
  PRODUCT VARCHAR(128) NOT NULL,
  STATUS VARCHAR(32) NOT NULL ,
  AMOUNT DECIMAL(6,2) NOT NULL
);


alter table AUTHORITIES
add FOREIGN KEY  (USERNAME)
  REFERENCES users(USERNAME);

ALTER TABLE DEPOT
ADD FOREIGN KEY (USER_ID)
REFERENCES USERS(ID);

create index my_depot_idx on DEPOT(USER_ID);